<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>js-Error</title>
</head>
<body>
    <script type="text/javascript">
        try{
            notExists();
        }catch(e){
            alert(e.name+':'+e.message);
        }
        alert('this is a test');
        try{
            var n=2;
            if(n==0){
                throw new Error('0不能当做除数');
            }else {
                alert(4/n);
            }
        }catch (e){
            alert(e.name+':'+e.message);
        }finally {
            alert('我总是被调用');
        }
        try{
            notExists();
        }catch (e){
            if (e instanceof EvalError){
                alert('EvalError'+e.message);
            }else if (e instanceof  RangeError){
                alert('RangeError'+e.message);
            }else if (e instanceof TypeError){
                alert('TypeError'+e.message);
            }else {
                alert('其他Error');
            }
        }
        function myError(msg) {
            this.name='myError';
            this.message=msg||'默认的自定义错误信息';
        }
        myError.prototype=Object.create(Error.prototype);
        myError.prototype.constructor=myError;
        try{
            throw new myError();
        }catch (e){
            console.log(e.name+':'+e.message);
        }
        try{
            throw new myError('测试自定义的错误信息');
        }catch (e){
            console.log(e.name+':'+e.message);
        }
    </script>
</body>
</html>